language: r
pandoc_version: 2.2
sudo: false
install:
  - pip install --user pandocfilters
  - wget -qO- https://github.com/hakimel/reveal.js/archive/3.7.0.tar.gz | tar -xvz
  - mv reveal* reveal.js

script:
  - pandoc -t revealjs -s Readme.md -o index.html
  - touch .nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: .
